/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Banner: typeof import('./components/Banner.vue')['default']
    BottomDrawer: typeof import('./components/BottomDrawer.vue')['default']
    CenterDialog: typeof import('./components/CenterDialog.vue')['default']
    ClickButton: typeof import('./components/ClickButton.vue')['default']
    Confirm: typeof import('./components/Confirm.vue')['default']
    CustomerEditHead: typeof import('./components/customerEdit/Head.vue')['default']
    CustomerHead: typeof import('./components/customer/Head.vue')['default']
    CustomerItem: typeof import('./components/customer/Item.vue')['default']
    CustomerQuery: typeof import('./components/customer/Query.vue')['default']
    CustomerSelector: typeof import('./components/CustomerSelector.vue')['default']
    CustomVisitHead: typeof import('./components/customVisit/Head.vue')['default']
    CustomVisitItem: typeof import('./components/customVisit/Item.vue')['default']
    CustomVisitQuery: typeof import('./components/customVisit/Query.vue')['default']
    DeptHead: typeof import('./components/dept/Head.vue')['default']
    DeptItem: typeof import('./components/dept/Item.vue')['default']
    DeptMemberHead: typeof import('./components/deptMember/Head.vue')['default']
    DeptQuery: typeof import('./components/dept/Query.vue')['default']
    EditUserHead: typeof import('./components/editUser/Head.vue')['default']
    EditVisitsHead: typeof import('./components/editVisits/Head.vue')['default']
    FormDate: typeof import('./components/form/Date.vue')['default']
    FormImage: typeof import('./components/form/Image.vue')['default']
    FormInput: typeof import('./components/form/Input.vue')['default']
    FormMap: typeof import('./components/form/Map.vue')['default']
    FormSelect: typeof import('./components/form/Select.vue')['default']
    HeadBar: typeof import('./components/HeadBar.vue')['default']
    InputConfirm: typeof import('./components/InputConfirm.vue')['default']
    MainCard: typeof import('./components/main/Card.vue')['default']
    MainExamCard: typeof import('./components/main/ExamCard.vue')['default']
    MainExamTag: typeof import('./components/main/ExamTag.vue')['default']
    MainHead: typeof import('./components/main/Head.vue')['default']
    MainItem: typeof import('./components/main/Item.vue')['default']
    MainQueryBar: typeof import('./components/main/QueryBar.vue')['default']
    MainVisitItem: typeof import('./components/main/VisitItem.vue')['default']
    MemberSelector: typeof import('./components/MemberSelector.vue')['default']
    MyHeadBar: typeof import('./components/my/HeadBar.vue')['default']
    OutcomeTypeHead: typeof import('./components/outcomeType/Head.vue')['default']
    QrCode: typeof import('./components/QrCode.vue')['default']
    SelectBar: typeof import('./components/SelectBar.vue')['default']
    ShareEditHead: typeof import('./components/shareEdit/Head.vue')['default']
    TabBarCustomer: typeof import('./components/tabBar/customer.vue')['default']
    TabBarLogin: typeof import('./components/tabBar/login.vue')['default']
    TabBarMain: typeof import('./components/tabBar/main.vue')['default']
    TabBarMy: typeof import('./components/tabBar/my.vue')['default']
    Toast: typeof import('./components/Toast.vue')['default']
    UserHead: typeof import('./components/user/Head.vue')['default']
    UserItem: typeof import('./components/user/Item.vue')['default']
    UserQuery: typeof import('./components/user/Query.vue')['default']
    VerticalPage: typeof import('./components/VerticalPage.vue')['default']
    VisitDetailHead: typeof import('./components/visitDetail/Head.vue')['default']
    VisitRecordHead: typeof import('./components/visitRecord/Head.vue')['default']
    VisitRecordQuery: typeof import('./components/visitRecord/Query.vue')['default']
    VisitResultHead: typeof import('./components/visitResult/Head.vue')['default']
    VisitTypeHead: typeof import('./components/visitType/Head.vue')['default']
  }
}
