/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AIcon: typeof import('./components/AIcon.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ARating: typeof import('./components/ARating.vue')['default']
    Banner: typeof import('./components/Banner.vue')['default']
    BottomDrawer: typeof import('./components/BottomDrawer.vue')['default']
    CenterDialog: typeof import('./components/CenterDialog.vue')['default']
    CheckboxItem: typeof import('./components/CheckboxItem.vue')['default']
    ClickButton: typeof import('./components/ClickButton.vue')['default']
    Confirm: typeof import('./components/Confirm.vue')['default']
    DateRangePicker: typeof import('./components/DateRangePicker.vue')['default']
    FormDate: typeof import('./components/form/Date.vue')['default']
    FormImage: typeof import('./components/form/Image.vue')['default']
    FormInput: typeof import('./components/form/Input.vue')['default']
    FormMap: typeof import('./components/form/Map.vue')['default']
    FormSelect: typeof import('./components/form/Select.vue')['default']
    HeadBar: typeof import('./components/HeadBar.vue')['default']
    InputConfirm: typeof import('./components/InputConfirm.vue')['default']
    MyHeadBar: typeof import('./components/My/HeadBar.vue')['default']
    PageActivityHomeHead: typeof import('./components/page/activity/home/Head.vue')['default']
    PageActivityListHead: typeof import('./components/page/activity/list/Head.vue')['default']
    PageActivityReleaseHead: typeof import('./components/page/activity/release/Head.vue')['default']
    PageGroupActivityHead: typeof import('./components/page/group/activity/Head.vue')['default']
    PageGroupHead: typeof import('./components/page/group/Head.vue')['default']
    PageGroupHomeHead: typeof import('./components/page/group/home/Head.vue')['default']
    PageMainHead: typeof import('./components/page/main/Head.vue')['default']
    PageMemberHead: typeof import('./components/page/member/Head.vue')['default']
    PageMemberHomeHead: typeof import('./components/page/member/home/Head.vue')['default']
    PageMyActivityHead: typeof import('./components/page/my/activity/Head.vue')['default']
    PageMyHead: typeof import('./components/page/my/Head.vue')['default']
    PageMyMemberHead: typeof import('./components/page/my/member/Head.vue')['default']
    PageMyOrderHead: typeof import('./components/page/my/order/Head.vue')['default']
    PageMyPointHead: typeof import('./components/page/my/point/Head.vue')['default']
    PageMyProfileHead: typeof import('./components/page/my/profile/Head.vue')['default']
    PageShopCartHead: typeof import('./components/page/shop/cart/Head.vue')['default']
    PageShopHead: typeof import('./components/page/shop/Head.vue')['default']
    PageShopHomeHead: typeof import('./components/page/shop/home/Head.vue')['default']
    PageShopOrderHead: typeof import('./components/page/shop/order/Head.vue')['default']
    QrCode: typeof import('./components/QrCode.vue')['default']
    SelectBar: typeof import('./components/SelectBar.vue')['default']
    TabBarGroup: typeof import('./components/tabBar/group.vue')['default']
    TabBarMain: typeof import('./components/tabBar/main.vue')['default']
    TabBarMember: typeof import('./components/tabBar/member.vue')['default']
    TabBarMy: typeof import('./components/tabBar/my.vue')['default']
    TabBarOrder: typeof import('./components/tabBar/order.vue')['default']
    TabBarShop: typeof import('./components/tabBar/shop.vue')['default']
    Toast: typeof import('./components/Toast.vue')['default']
    VerticalPage: typeof import('./components/VerticalPage.vue')['default']
  }
}
