/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

export interface NavigateToOptions {
  url: "/pages/main/index" |
       "/pages/customer/edit" |
       "/pages/customer/index" |
       "/pages/main/visitDetail" |
       "/pages/main/visitResult" |
       "/pages/my/editUser" |
       "/pages/my/index" |
       "/pages/my/outcomeType" |
       "/pages/my/user" |
       "/pages/my/visitRecord" |
       "/pages/my/visitType";
}
interface RedirectToOptions extends NavigateToOptions {}

export interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
