/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/main/index" |
       "/pages/activity/home" |
       "/pages/activity/list" |
       "/pages/activity/release" |
       "/pages/group/activity" |
       "/pages/group/home" |
       "/pages/member/home" |
       "/pages/my/activity" |
       "/pages/my/member" |
       "/pages/my/order" |
       "/pages/my/point" |
       "/pages/my/profile" |
       "/pages/shop/cart" |
       "/pages/shop/home" |
       "/pages/shop/order";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
